SOURCES=$(wildcard *.asm)
OBJECTS=$(SOURCES:%.asm=%.prg)

# Build the KICK ASSEMBLER PATH
ifndef ASMPATH
$(info Using default Kickasm path, to change # export ASMPATH=<path>)
ASM = java -jar ../../KickAss.jar
else
ASM = java -jar ${ASMPATH}
endif

# BUILD the C64 debugger path
ifndef C64DEBUGGERPATH
$(info Using default C64Debugger path, to change export C64DEBUGGERPATH=<path>)
C64DEBUGGERPATH=../../../c64debugger/C64Debugger/c64debugger
else
C64DEBUGGERPATH=${C64DEBUGGERPATH}
endif

all: $(OBJECTS)

# Run prg file 'make run-'name' (without prg)
run-%: %.prg $(OBJECTS)
	x64 $<

# Run debugger on one of the generated programs
debug-%: %.prg $(OBJECTS)
	${C64DEBUGGERPATH} $< || true

# Build the prg files
%.prg: %.asm 
	$(ASM) $<

# Remove all prg files generated by this Makefile
clean:
	rm $(OBJECTS) || true
